# Generated by Django 6.1.2 on 2026-10-07 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('llc_name', models.CharField(blank=True, max_length=150)),
                ('truck_number', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.CharField(max_length=50)),
                ('payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('miles', models.DecimalField(decimal_places=1, default=0.0, max_digits=8)),
                ('fuel_surcharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('origin_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_arrival', models.TimeField(blank=True, null=True)),
                ('pickup_departure', models.TimeField(blank=True, null=True)),
                ('destination_date', models.DateField(blank=True, null=True)),
                ('destination_arrival', models.TimeField(blank=True, null=True)),
                ('destination_departure', models.TimeField(blank=True, null=True)),
                ('tolls', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('incidentals', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuelExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('DEF', 'DEF'), ('REEFER', 'Reefer')], default='DIESEL', max_length=10)),
                ('gallons', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='tracker.trip')),
            ],
        ),
    ]
