# Generated by Django 6.1.2 on 2026-10-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-trip_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='trip',
            name='bol_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_odometer',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_gallons',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_odometer',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('Dispatched', 'Dispatched'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Settled', 'Settled')], default='Delivered', max_length=30),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
