# Generated by Django 6.1.2 on 2026-10-09 11:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_trip_options_trip_bol_number_trip_end_odometer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-pickup_date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='miles',
            new_name='miles_total',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='end_odometer',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_odometer',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='tolls',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_date',
        ),
        migrations.AddField(
            model_name='trip',
            name='cat_scale',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='CAT Scale'),
        ),
        migrations.AddField(
            model_name='trip',
            name='customer_name',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddField(
            model_name='trip',
            name='def_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='DEF'),
        ),
        migrations.AddField(
            model_name='trip',
            name='reefer_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Reefer'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='bol_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='BOL #'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='fuel_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Price Per Gallon'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Pay'),
        ),
        migrations.CreateModel(
            name='FuelStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_location', models.CharField(blank=True, max_length=100)),
                ('gallons', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('price_per_gallon', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_stops', to='tracker.trip')),
            ],
        ),
        migrations.DeleteModel(
            name='FuelExpense',
        ),
    ]
