# Generated by Django 6.1.2 on 2026-10-09 11:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_trip_options_rename_miles_trip_miles_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='deadhead_miles',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8, verbose_name='Deadhead Miles'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='miles_total',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=8, verbose_name='Loaded Miles'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('Quote / Planner', 'Quote / Mission Planner'), ('Booked', 'Booked / Scheduled'), ('Dispatched', 'Dispatched'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Settled', 'Settled')], default='Delivered', max_length=30),
        ),
    ]
