# Generated by Django 6.1.2 on 2026-10-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_trip_deadhead_miles_alter_trip_miles_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='tier',
            field=models.CharField(choices=[('BETA_LIFETIME', 'Beta VIP (Lifetime Free)'), ('ACTIVE_PAID', 'Active Paid Subscriber'), ('TRIAL', 'Free Trial'), ('EXPIRED', 'Subscription Expired')], default='BETA_LIFETIME', max_length=30),
        ),
    ]
